const fs = require('node:fs');
const vm = require('node:vm');
const assert = require('node:assert/strict');
const QuestZones = require('./zones.js');
const QuestLayers = require('./scene-layers.js');
const QuestRules = require('./rules.js');
const source = fs.readFileSync(`${__dirname}/app.js`, 'utf8').split('let project=sample();')[0];
vm.runInNewContext(source + `
  const p = sample();
  validate(p);
  assert.equal(p.scenes.length, 4);
  p.scenes[0].choices[0].target = 'missing';
  assert.throws(() => validate(p));
  const q = sample();
  q.scenes[1].id = q.scenes[0].id;
  assert.throws(() => validate(q));
  const r = sample();
  r.start = 'missing';
  assert.throws(() => validate(r));
  assert.throws(() => validate({version: 1, title: 'Empty', scenes: []}));
  const imageProject = sample();
  imageProject.scenes[0].image = 'data:image/png;base64,aGVsbG8=';
  imageProject.scenes[0].choices[0].zone = [{mode:'paint', radius:.05, points:[[0,.5],[1,.5]]}];
  validate(JSON.parse(JSON.stringify(imageProject)));
  imageProject.scenes[0].choices[0].zone[0].points[0][0] = -1;
  assert.throws(() => validate(imageProject));
  imageProject.scenes[0].choices[0].zone = [];
  imageProject.scenes[0].image = 'https://example.com/tracking.png';
  assert.throws(() => validate(imageProject));
  assert.throws(() => validate({...sample(), scenes:[null]}));
  const conditional = sample();
  conditional.variables = [{id:'strength',type:'stat',name:'Сила',initial:5}];
  conditional.scenes[0].choices[0].conditions = [{variable:'strength',op:'gte',value:5}];
  validate(JSON.parse(JSON.stringify(conditional)));
  conditional.scenes[0].choices[0].conditions[0].variable = 'missing';
  assert.throws(() => validate(conditional));
`, {assert, QuestZones, QuestRules, QuestLayers});

const paint = {mode:'paint', radius:.1, points:[[.2,.5],[.8,.5]]};
const erase = {mode:'erase', radius:.05, points:[[.5,.5]]};
assert.equal(QuestZones.contains([paint], .5, .5, 1000, 500), true, 'segment interior is painted');
assert.equal(QuestZones.contains([paint], .16, .5, 1000, 500), true, 'round cap is painted');
assert.equal(QuestZones.contains([paint], .5, .7, 1000, 500), false, 'outside stroke is empty');
assert.equal(QuestZones.contains([paint,erase], .5, .5, 1000, 500), false, 'eraser removes coverage');
assert.equal(QuestZones.contains([paint,erase,paint], .5, .5, 1000, 500), true, 'painting restores coverage');
assert.equal(QuestZones.contains([paint], .16, .5, 500, 250), true, 'resize preserves hit test');
assert.equal(QuestZones.hit([{zone:[paint]}, {zone:[paint,erase]}], .5,.5,1000,500), 0, 'erased top zone reveals lower action');
assert.equal(QuestZones.hit([{zone:[paint]}, {zone:[paint]}], .5,.5,1000,500), 1, 'last action wins overlap');
assert.equal(QuestZones.hit([{zone:[paint]}], .5,.9,1000,500), -1, 'empty image area does nothing');
assert.equal(QuestZones.validStrokes([{...paint,radius:NaN}]),false);
assert.equal(QuestZones.validStrokes([{...paint,points:[]}]),false);
assert.equal(QuestZones.validStrokes([{...paint,mode:'unknown'}]),false);
console.log('PASS: legacy and image projects, import validation, paint, erase, repaint, overlap, resizing, empty-area hit tests');
